# Generated by Django 5.0.4 on 2024-05-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='nama',
            field=models.CharField(max_length=30),
        ),
    ]
